name: planckton
channels:
  - conda-forge
  - mosdef
  - omnia
dependencies:
  - py3dmol #
  - openbabel
  - jupyterlab #
  - nodejs>=10 #
  - openbabel
  - python=3.7
  - pip=20.2
  - numpy=1.19
  - foyer=0.7.6
  - gsd=2.2.0
  - mbuild=0.10.9
  - hoomd=2.9.3
  - openmm=7.4.2
  - signac=1.5.0
  - pip:
    - pytest
    - pytest-cov
    - git+https://bitbucket.org/cmelab/cme_utils.git
    - "--editable=git+https://github.com/rsdefever/GAFF-foyer.git#egg=gaff_foyer-master"
    - git+https://github.com/cmelab/planckton@fix_setup
