name: planckton
channels:
  - conda-forge
  - omnia #
dependencies:
  - ele=0.1.0
  - foyer=0.7.7
  - gsd=2.2.0
  - hoomd=2.9.3
  - mdtraj=1.9.5 #
  #- mbuild=0.10.12
  - numpy=1.19
  - openbabel=3.1.1
  - openmm>=7.5
  - jupyter
  - oset=0.1.3 #
  - packmol=20 #
  - pip=20.2
  - pytest
  - pytest-cov
  - python=3.7
  - rdkit
  - signac=1.6.0
  - signac-flow=0.13.0
  - unyt=2.8.0
  - pip:
    - git+https://github.com/mosdef-hub/mbuild
    - git+https://github.com/rsdefever/antefoyer.git
    - git+https://github.com/cmelab/planckton@v0.4.0
