# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cmelab/planckton:0.0.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            pip install black pytest pytest-cov
            pip install -e .

      - run:
          name: style-check
          command: |
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            black --diff --check planckton/ examples/ tests/

      - run:
          name: run tests
          command: |
            pytest --cov=planckton
      
      - run:
          name: upload coverage
          command: |
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

      - store_artifacts:
          path: test-reports
          destination: test-reports
