name: build_cpu_tagged

on:
  push:
    branches: [ master ]
    # Run when a new tag is pushed
    tags:
        - *
  pull_request:
    branches: [ master ]
    tags:
        - *

jobs:
  build_cpu:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: tag number
        run : echo ${{ github.event.release.tag_name }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./containers/dockerfile_cpu
          push: true
          tags: cmelab/planckton_cpu:${{ github.event.release.tag_name }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
