
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup miniconda
      uses: goanpeca/setup-miniconda@v1.6.0
      with:
        # https://github.com/goanpeca/setup-miniconda
        activate-environment: planckton
        environment-file: environment.yml
        auto-activate-base: false
        
    - name: Run pytest with coverage report
      shell: bash -l {0}
      run: |
          python -m pip install pytest pytest-cov
          python -m pytest --cov=./ --cov-report=xml
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
