
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: cmelab/planckton_cpu:0.1.4

    steps:
    - uses: actions/checkout@v2
 
    - name: Run pytest with coverage report
      run: |
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
